// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package product

import (
	"database/sql"
	"time"
)

type Category struct {
	ID   int32
	Name string
}

type Product struct {
	ID            int32
	Name          string
	Description   sql.NullString
	OriginalPrice float64
	CategoryID    int32
	CreatedAt     time.Time
	LastUpdatedAt time.Time
}

type ProductImage struct {
	ID        int32
	ImageUrl  string
	ProductID int32
}
